### ISSUE TITLE
atividade true or false avisar quando o usuário não marcou todas

### ISSUE THREAD

**Issue by santagada** [hacklabr/timtec#134]
Hoje a atividade trueorfalse só avisa de erro ou acerto, mas quando o usuário não respondeu todas as perguntas ela sempre diz que esta errado.

**Comment by robertkapa** [comment]
https://github.com/institutotim/timtec/issues/20

**Comment by brunosmartin** [comment]
Foi resolvida esta?!

**Comment by robertkapa** [comment]
Reescrevi toda a issue aqui dando detalhes sobre a implementação da mesma, @brunosmartin https://github.com/institutotim/timtec/issues/20 Estou pegando algumas issues daqui para o @moacirmoda porque estavam no relatório das meninas.
