### ISSUE TITLE
quando cria um novo curso, a página de material do curso não é criada automaticamente

### ISSUE THREAD

**Issue by andersonorui** [hacklabr/timtec#313]
criei um novo curso e depois tentei entrar na página do material do curso e deu erro

**Comment by barraponto** [comment]
fechou mas resolveu, @brunosmartin ?

**Comment by brunosmartin** [comment]
Sim, resolvido. Olha o método save do modelo Course
Em 02/01/2015 15:47, "Capi Etheriel" <notifications@github.com> escreveu:
