### ISSUE TITLE
Carregar a fixture prod.json resulta em erros  

### ISSUE THREAD

**Issue by barraponto** [hacklabr/timtec#503]
O que é a fixture `prod.json`? É relativo à plataforma ou específico do projeto da Tim?
Carregá-la logo após o make (com `./manage.py loaddata prod`) resulta em erro:

    ValueError: Problem installing fixture 'timtec/core/fixtures/prod.json': Cannot assign None: "StudentProgress.unit" does not allow null values.

**Comment by brunosmartin** [comment]
Arquivo removido
