### ISSUE TITLE
Grupos e permissões não são gerados/configurados na instalação

### ISSUE THREAD

**Issue by barraponto** [hacklabr/timtec#518]
E isso resulta num monte de telas quebradas.

Tem uma configuração básica no https://github.com/hacklabr/timtec/blob/master/core/fixtures/minimal.json mas ela foi copiada de uma versão antiga do `production.json`. Foi por isso que eu abri a issue #503 , porque eu estava me baseando nessa fixture pra saber que permissões eu preciso atribuir no `minimal.json`.

De todo modo, mesmo que esteja no `minimal.json`, a importação precisa estar no make, ou a gente pode simplesmente enfiar no `initial_data.json` (com o porém de que ele é importado a cada sempre que se roda o `migrate`).

**Comment by brunosmartin** [comment]
Isso foi corrigido na versão 3.0. Agora as permissões são por cursos, e só há a permissão global de administrador, suportada por um campo do usuário.
