### ISSUE TITLE
Leia Mais / Baixar o curso

### ISSUE THREAD

**Issue by gobbibruno** [hacklabr/timtec#535]
O "Baixar o Curso" não aparece para todos os cursos. A descrição é muito grande. Fazer um "leia mais" para que todas as descrições apareçam do mesmo tamanho e, consequentemente, o "Baixar o curso" apareça.

![leiamais](https://cloud.githubusercontent.com/assets/15158985/11073535/2cc89728-87d2-11e5-91c6-7304da766c8c.png)

**Comment by brunosmartin** [comment]
O download só aparece qdo tem o arquivo no post do curso.

Acho q os q não tão aparecendo o botão é pq não foi feito o upload do curso.

Verificou isso?
Em 10/11/2015 17:52, "Gobbi" <notifications@github.com> escreveu:
