### ISSUE TITLE
Corrigir leiaute de aceitação dos termos de uso para usuário já registrado

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/timtec#547]
http://localhost:8080/accept_terms/

![bug timtec](https://cloud.githubusercontent.com/assets/69956/11445178/1a3c579c-9511-11e5-837a-4790b9c2c0dd.png)

**Comment by robertkapa** [comment]
Não foi corrigido ainda. http://demo.timtec.com.br/accept_terms/

**Comment by robertkapa** [comment]
https://github.com/institutotim/timtec/issues/21
