### ISSUE TITLE
Implementar autenticação no provedor de Openid do Moodle

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/timtec#553]
autenticação para o TIM Tec, consumindo o provedor de Openid do Moodle. Isto resolveria o problema de Login único (SSO) da maioria dos Institutos Federais, que já tem uma integração dos próprios sistema acadêmicos com o Moodle, reduzindo drasticamente o custo de suporte. Para isso, escolhemos o plugins Moodle OpenID Provider (https://moodle.org/plugins/view/local_openid_idp) e esta implementação será voltada para ele.

- [ ] Criar vagrant (docker?) com o moodle, versão 2.x (maior suportada pelo plugin) para dev e validação pelo cliente
- [ ] Configurar o django all auth para fazer a autenticação no provedor de Openid do Moodle
- [ ] Documentar como fazer isso no wiki do timtec, colocando a versão do Moodle necessaria, o plugin, etc, pois os Instituto Federais vão usar esta documentação para fazer esta configuração

**Comment by fabiomontefuscolo** [comment]
Para testes, usei uma maquina virtual pré-configurada com Moodle, que pode ser encontrada em https://www.turnkeylinux.org/moodle.

O plugin pode ser encontrado em http://vcs.uhoreg.ca/git/cgit/moodle-local_openid_idp/ mas está parado a cerca de 3 anos.

O Moodle que usei era o 3.0 e funcionou para testar o login no timtec. Um Moodle >= 2.1 e <= 2.7 pode ter menus e atalhos melhores, pois o plugin foi desenhado para essas verões.

O endereço `http://instancia_de_moodle/local/openid_idp/` deve ser colocado no arquivo settings do Django para que a opção de login via OpenID apareça.
