### ISSUE TITLE
Ao importar curso, se der erro a mensagem de erro só aparece depois que pressionar <ctrl>+<r>.

### ISSUE THREAD

**Issue by kelsoncm** [hacklabr/timtec#584]
Este problema foi detectado no Safari.

Ambiente de teste: **v3.1**, Mac OS X 10.11.4 El Captain, Arquivo de 54MB - producaodetextos.tar.gz, **client_max_body_size 100m;** no arquivo **/etc/nginx/sites-enabled/timtec-production**.

Browser: **Safari 9.1**
Access log: "POST /admin/course/import/ HTTP/1.1" 400 0 "http://mooc.ifrn.edu.br/admin/courses/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17"
Comportamento: Aparece um dialogo HTML com a mensagem "**Erro ao importar arquivo de curso!**" e o botão **Fechar**.

Browser: **Firefox 44.0.2**
Access log: "POST /admin/course/import/ HTTP/1.1" 400 0 "http://mooc.ifrn.edu.br/admin/courses/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0"
Comportamento: Aparece uma mensagem e rapidamente desaparece uma mensagem "**Erro ao importar arquivo de curso!**".

Browser: **Chrome 49**
Access log: "POST /admin/course/import/ HTTP/1.1" 400 0 "http://mooc.ifrn.edu.br/admin/courses/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
Comportamento: Não aparece mensagem alguma.

**Comment by robertkapa** [comment]
Não consegui reproduzir o erro.

**Comment by kelsoncm** [comment]
Robert,

Acredito que possamos fechar pois o cenário é muito específico.

O erro só ocorreu comigo em uma VPN ou rede externa pois o upload não concluía, então eu atualizava a página e a requisição era encerrada e gerava o log visto no nginx.

Hoje fiz o teste aqui na rede interna e funcionou!
