### ISSUE TITLE
Tornar curso público/rascunho visível para alunos

### ISSUE THREAD

**Issue by GustavoVS** [hacklabr/timtec#595]
A opção de tornar o curso público ou rascunho está visível em telas pequenas (sm) para alunos. 
A alteração não é salva.

![curso_issue](https://cloud.githubusercontent.com/assets/7750643/15153559/04a44a36-16b0-11e6-8a98-6ccc2a5240a0.png)

**Comment by robertkapa** [comment]
descrição do bug reescrita: https://github.com/institutotim/timtec/issues/15
