### ISSUE TITLE
Atualizar angular-ui bootstrap

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/timtec#600]
O Modais mudaram bastante nas novas versões, e é preciso refatorar.
http://stackoverflow.com/questions/35395557/angular-unknown-provider-modalprovider-modal-controller

Estávamos usando esta versão: http://angular-ui.github.io/bootstrap/versioned-docs/0.12.1/#/modal
E agora precisamos reescrever para isso:
http://angular-ui.github.io/bootstrap/#/modal

- [ ] administration/static/js/course-permissions/controllers.js - PermissionsController

- [ ] administration/static/js/courses/controllers.js - CoursesAdminController

- [ ] administration/static/js/courses/controllers.js - CourseListByUserRoleController
       
- [ ] administration/static/js/messages/controllers.js - NewMessageController

- [ ] administration/static/js/messages/controllers.js - MessagesListController

- [ ] administration/static/js/new-course/controllers.js - CourseEditController

- [ ] administration/static/js/users-admin/controllers.js - UsersAdminController

- [ ] core/static/js/certificate/controllers.js - ClassEvaluationsController

- [ ] core/static/js/lesson/controllers.js - MainCtrl
      
- [ ] core/static/js/my-courses/controllers.js - UserCourseListController

- [ ] core/static/js/my-courses/controllers.js - UserCertificatesController

- [ ] core/static/js/my-courses/controllers.js - AssistantCourseListController

- [ ] core/static/js/my-courses/controllers.js - CoordinatorCourseListController
     
- [ ] forum/static/js/forum/controllers.js - InlineForumCtrl

**Comment by fredericksilva** [comment]
Fiz algumas alterações adicionando a nova forma de chamar a função Modal e tbm troquei a forma de instanciar. Agora vou passar um pente fino nas modificações.
