### ISSUE TITLE
Implementar arquitetura para chat e notificações

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/timtec#601]
https://blog.heroku.com/archives/2016/3/17/in_deep_with_django_channels_the_future_of_real_time_apps_in_django

https://channels.readthedocs.io/en/latest/

**Comment by tonylampada** [comment]
Tem uma alternativa ao django_channels, que é o tornado.

Eu resolvi um problema semelhante com uma arquitetura que é mais ou menos o seguinte:

Cria uma aplicação separada - um servidor de websockets, feita com tornado. Esse cara é um serviço genérico de websockets, não precisa nem ter um banco de dados. Ele pode ser acessado pelo backend Django e pelo browser, e expõe APIs diferentes pra cada um desses dois clientes:

API para o backend Django:

* get_token_for_channel(channelid) - retorna um token aleatório que um browser pode usar pra abrir um websockets
* send(channelid, msg) - envia uma mensagem para todos os websockets conectados no canal channelid

API disponível para o browser:

* /opensocket?token=xxx

A autenticação do django-tornado pode ser tão simples quanto uma senha mestre, configurada na forma variável de ambiente nos dois backends.

A autenticação browser-tornado pode ser simplesmente baseado no referrer pra ver o request vem mesmo do teu site.

Faça com que ao logar um usuário, o Django peça pro tornado um novo token de websocket:

`token = websocketadapter.get_token_for_channel(username)`

Envie esse token pro browser de modo que ele possa usar javascript pra abrir o websocket se conectando em `/opensocket?token=xxx`

Sempre que quiser enviar uma mensagem de chat ou uma notificação pra um usuário qualquer, o django pede pro tornado:

`websocketadapter.send(username, json.dumps(msgdict))`

O javascript precisa saber o que fazer com os diferentes tipos de mensagem que chegam pelo websocket.

Publique esse serviço de websocket no github e no docker para que o resto do mundo possa aproveitar tb (uma vez que ele pode ser usado em contextos totalmente diferentes do timtec)

Só uma ideia :)

**Comment by tonylampada** [comment]
Ah, se vc quiser seguir por esse caminho, tô com a impressãoque isso aqui pode ser um bom ponto de partida:
* https://github.com/hiroakis/tornado-websocket-example
* https://hub.docker.com/r/hiroakis/tornado-websocket-example/
